### ISSUE TITLE
Should we add authors to articles?

### ISSUE THREAD

**Issue by caro401** [codexfelis/oratio#13]
While its mostly us two writing, maybe isn't so relevant (but maybe it is?), but if we get external contributors authoring it might be nice to credit them clearly. Not sure what's the best way to do this if it is useful - name with link to website/preferred social media is maybe sufficient, or would we want full-on author bio pages?

**Comment by danwaterfield** [comment]
Easiest option at the moment is name / link. If a sizeable number of contributors turn out to be not-us then we can make author pages later.
